name: Erlang CI

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp: [23.3, 24.3, 25.0]

    steps:
    - uses: actions/checkout@v3
    - uses: erlef/setup-beam@v1
      id: setup-beam
      with:
        otp-version: ${{matrix.otp}}
        rebar3-version: '3.18.0'
    - name: Restore _build
      uses: actions/cache@v3
      with:
        path: _build
        key: "_build-cache-for\
              -os-${{runner.os}}\
              -otp-${{steps.setup-beam.outputs.otp-version}}\
              -rebar3-${{steps.setup-beam.outputs.rebar3-version}}\
              -hash-${{hashFiles('rebar.lock')}}"
    - name: Restore rebar3's cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/rebar3
        key: "rebar3-cache-for\
              -os-${{runner.os}}\
              -otp-${{steps.setup-beam.outputs.otp-version}}\
              -rebar3-${{steps.setup-beam.outputs.rebar3-version}}\
              -hash-${{hashFiles('rebar.lock')}}"
    - name: Compile
      env:
          ERL_FLAGS: "-enable-feature all"
      run: rebar3 compile
    - name: Format check
      env:
          ERL_FLAGS: "-enable-feature all"
      run: rebar3 format --verify
    - name: Run tests and verifications
      env:
          ERL_FLAGS: "-enable-feature all"
      run: rebar3 test
